## Question1

In [1]:
import numpy as np

G is the eigen vector which is found by using the formula given in the pdf

In [2]:
G = np.matrix([[0,1/4,0,1/4,1/4,1/4],[0,0,0.5,0.5,0,0],[0,0,0,0,1,0],[0,0,0,0,1,0],[0.5,0,0,0.5,0,0],[0,0,0,0,1,0]]).transpose()

In [3]:
G

matrix([[0.  , 0.  , 0.  , 0.  , 0.5 , 0.  ],
        [0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.5 , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.5 , 0.  , 0.  , 0.5 , 0.  ],
        [0.25, 0.  , 1.  , 1.  , 0.  , 1.  ],
        [0.25, 0.  , 0.  , 0.  , 0.  , 0.  ]])

lambda represent the eigen value and v represent the eigen vector

G⃗v = λ⃗v

## Question 2

In [4]:
eigval,eigvect=np.linalg.eig(G)

In [5]:
eigval

array([ 1.00000000e+00+0.j        , -1.39845075e-01+0.39240258j,
       -1.39845075e-01-0.39240258j, -7.20309850e-01+0.j        ,
        2.96003466e-17+0.j        , -2.47220661e-17+0.j        ])

In [6]:
eigvect

matrix([[ 3.77123617e-01+0.j        , -5.77040252e-01+0.j        ,
         -5.77040252e-01-0.j        , -4.89508017e-01+0.j        ,
          6.57629212e-16+0.j        , -1.20047319e-16+0.j        ],
        [ 9.42809042e-02+0.j        ,  1.16252589e-01+0.32620252j,
          1.16252589e-01-0.32620252j,  1.69894948e-01+0.j        ,
          1.00171455e-16+0.j        ,  3.18707336e-17+0.j        ],
        [ 4.71404521e-02+0.j        ,  3.21965131e-01-0.2628717j ,
          3.21965131e-01+0.2628717j , -1.17931851e-01+0.j        ,
         -6.78675509e-01+0.j        ,  1.14131990e-01+0.j        ],
        [ 5.18544973e-01+0.j        , -1.38822532e-01+0.06333082j,
         -1.38822532e-01-0.06333082j, -4.37544920e-01+0.j        ,
          7.32465806e-01+0.j        , -7.57230559e-01+0.j        ],
        [ 7.54247233e-01+0.j        ,  1.61392475e-01-0.45286417j,
          1.61392475e-01+0.45286417j,  7.05194893e-01+0.j        ,
         -2.83154890e-16+0.j        , -4.19341548e-16+0.j 

# Diagonalization

To understand this concept you can refer this [page](https://www.geeksforgeeks.org/matrix-diagonalization/)

In [7]:
D=np.diag(eigval)
P = eigvect

In [8]:
A = np.dot(np.dot(P,D),np.linalg.inv(P))

In [9]:
A

matrix([[ 9.71445147e-17-3.41196830e-18j,
          0.00000000e+00+8.09702315e-18j,
         -5.55111512e-17+5.12747844e-19j,
          8.67361738e-17+1.82921273e-18j,
          5.00000000e-01-1.48616819e-18j,
          5.86336535e-16+3.87484767e-18j],
        [ 2.50000000e-01+7.47451163e-18j,
         -2.01135476e-16+2.08456324e-18j,
          1.19576916e-16+2.27980962e-18j,
         -1.02176478e-16+9.59229072e-19j,
          6.10706352e-17+7.98530396e-18j,
         -1.00429212e-16+1.76637521e-18j],
        [-5.55111512e-17-5.12915316e-17j,
          5.00000000e-01-5.87165126e-18j,
          1.64798730e-16+2.49088538e-18j,
          2.94902991e-17-4.45278853e-18j,
          6.93889390e-17-7.84108343e-19j,
          1.90819582e-17-5.52583780e-19j],
        [ 2.50000000e-01-3.32834868e-17j,
          5.00000000e-01+4.08744815e-18j,
          2.88831459e-16+2.84600141e-18j,
          1.96891115e-16+3.27078661e-18j,
          5.00000000e-01+5.64284520e-18j,
          6.91287305e-16+3.2204

In [10]:
np.array_equal(A,G)

False

clearly is visible that A and G don't match so G is not diagonalizable

## Question3

This is the main algorithm 

In [11]:
def page_rank(H,tol=1e-6,max_iter=100,beta=0.8):
    v1=np.array([[1/6,1/6,1/6,1/6,1/6,1/6]]).T
    c=(1-beta)*v1
    v0=v1
    for i in range(0,1001):
        v1= beta*(H @ v0)+c  
        if np.sum(abs(v1-v0)) < tol: 
            print('the value of k is equal to ',i)
            break
        v0=v1
    return v0

The vector which we get back from the page_rank function is basically the rank of the pages.Just for the purpose of better understanding I have multiplied by 100. You can refer [video](https://www.youtube.com/watch?v=gA3nDd_6QJM&list=PLJXHwy-4vGRY8QylvZomOvyYb1qZvTghk&index=6) to get deep knowledge

In [12]:
100*page_rank(G)

the value of k is equal to  24


matrix([[18.18758958],
        [ 6.97084558],
        [ 6.1216755 ],
        [24.61344399],
        [37.13559977],
        [ 6.97084558]])

# Question4

According to the question 4 the M is the eigen matrix of the following condition

In [13]:
M = np.matrix([[0,1/5,1/5,1/5,1/5,1/5],[1/5,0,1/5,1/5,1/5,1/5],[1/5,1/5,0,1/5,1/5,1/5],[1/5,1/5,1/5,0,1/5,1/5],[1/5,1/5,1/5,1/5,0,1/5],[1/5,1/5,1/5,1/5,1/5,0]])

In [14]:
M

matrix([[0. , 0.2, 0.2, 0.2, 0.2, 0.2],
        [0.2, 0. , 0.2, 0.2, 0.2, 0.2],
        [0.2, 0.2, 0. , 0.2, 0.2, 0.2],
        [0.2, 0.2, 0.2, 0. , 0.2, 0.2],
        [0.2, 0.2, 0.2, 0.2, 0. , 0.2],
        [0.2, 0.2, 0.2, 0.2, 0.2, 0. ]])

In [15]:
page_rank(M)

the value of k is equal to  0


array([[0.16666667],
       [0.16666667],
       [0.16666667],
       [0.16666667],
       [0.16666667],
       [0.16666667]])

In question 3
page1 -> rank3 page2 -> rank4 page3 -> rank5 page4 -> rank2 page5 -> rank1 page6 -> rank4

In question 4
All the rank of the pages is same 

# Question 5

According to the question 5 the N is the eigen matrix of the following condition

In [16]:
N = np.matrix([[0,1/4,0,1/4,1/4,1/4],[0,0,0.5,0.5,0,0],[0,0,0,0,1,0],[1/6,1/6,1/6,1/6,1/6,1/6],[0.5,0,0,0.5,0,0],[0,0,0,0,1,0]]).transpose()

In [17]:
100*page_rank(N)

the value of k is equal to  15


matrix([[17.36735197],
        [10.12559312],
        [10.70238405],
        [24.89105476],
        [26.78802298],
        [10.12559312]])

yes certainly previous rank are affected the page2 and page3 are demoted to rank 5 from rank 4. Page2 is promoted from rank 5 to rank 4